pep_version: "2.0.0"

project_name: hic_test

description: "PEP definition for the Hi-C workflow."

sample_table: hg38_test_sample.csv

# Project-level path variables
paths:
  data_dir: "/data2/litian/macrophage/script/hic_pipeline/distiller-sm/test/fastq"
  process_dir: "/storage/zhangkaiLab/hanlitian/macrophage/process"

